#
# Copyright 2023 Consolinno Energy GmbH
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += 1u0025_vilya.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing.o
endif
